project_id = "dhtlfdpvfintwvrxlkef"

[functions.weekly-backup]
verify_jwt = false

[functions.list-users]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false
